### ISSUE TITLE
robot coordinates and tf2

### ISSUE THREAD

**Issue by v-lavrushko** [ucuapps/robert#55]
I have some questions about working on issue #50:
1. Do I have to write aything into .simulation file?
2. Should I make new script and create topic with current coordinates of robot?

**Comment by AndriyPt** [comment]
@v-lavrushko could you please provide me link to .simulation file? I do not know about which file you are talking about :)
The task is about [generate_qr_code](https://github.com/ucuapps/robert/blob/kinetic-devel/robert_beverage/scripts/generate_qr_code) script. You should modify it and remove ability to read `x` and `y` coordinates from arguments but calculate them using `tf2` library as it is described in #50 .
After that encode into QR code as `x` and `y` coordinates.

**Comment by v-lavrushko** [comment]
In the tutorial, the second step is to write some lines into .simulation file.

**Comment by v-lavrushko** [comment]
And also, what is a map frame? I generated a graph for frames using view_frame and i didn't see it there

**Comment by AndriyPt** [comment]
@v-lavrushko it would be really helpful if you provide links to exact tutorial or code where you have issues. Else it is really hard to locate source of your question :)
Map frame is published by navigation stack.
You could launch it using command
`roslaunch robert_launch navigation.launch`
Please note that since we do not have proper map it will not localize robot correctly.
@deathtanks need to merge his map in order to get correct localization.
But if you need it only to test your tf reading code it should be sufficient :)
